<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:hl7="urn:hl7-org:v3"
             targetNamespace="urn:hl7-org:v3"
             name="ZorgRapportage">
   <documentation> WSDL implementatie van ZorgRapportage</documentation>
   <types>
      <xsd:schema targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified">
         <xsd:include schemaLocation="../schemas_codeGen/MCCI_IN000002.xsd"/>
      </xsd:schema>
      <xsd:schema targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified">
         <xsd:include schemaLocation="../schemas_codeGen/REPC_IN004014NL.xsd"/>
      </xsd:schema>
   </types>
   <message name="MCCI_IN000002">
      <part name="body" element="hl7:MCCI_IN000002"/>
   </message>
   <message name="REPC_IN004014NL">
      <part name="body" element="hl7:REPC_IN004014NL"/>
   </message>
   <portType name="ZorgRapportage_PortType">
      <operation name="ZorgRapportage_ZorgRapportage">
         <input message="hl7:REPC_IN004014NL"/>
         <output message="hl7:MCCI_IN000002"/>
      </operation>
   </portType>
   <binding type="hl7:ZorgRapportage_PortType" name="ZorgRapportage_Binding">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="ZorgRapportage_ZorgRapportage">
         <soap:operation soapAction="urn:hl7-org:v3/ZorgRapportage_ZorgRapportage"/>
         <input>
            <soap:body use="literal"/>
         </input>
         <output>
            <soap:body use="literal"/>
         </output>
      </operation>
   </binding>
   <service name="ZorgRapportage_Service">
      <port binding="hl7:ZorgRapportage_Binding" name="ZorgRapportage_Port">
<!-- Deze service location URI verwijst niet naar een echt bestaande webservice. -->
<soap:address location="http://www.xis.nl/ZorgRapportage"/>
      </port>
   </service>
</definitions>